stages:
  - deploy

.deploy:
  stage: deploy
  tags:
    - meao
    - aws
  before_script: # executed together in same shell context as scripts defined below
    - make clean
    - make build-ci
    - make push-ci
    - make test-ci

test:
  stage: deploy
  tags:
    - meao
    - aws
  only:
    - branches
  except:
    - dev
    - master
    - stage
    - prod
  script:
    - make clean
    - make build-ci
    - make test-ci

dev:
  extends: .deploy
  only:
    - dev
    - master
  variables:
    NAMESPACE: nucleus-dev
  script:
    - CLUSTER_NAME=frankfurt bin/update-config.sh


stage:
  extends: .deploy
  only:
    - stage
  variables:
    NAMESPACE: nucleus-stage
  script:
    - CLUSTER_NAME=frankfurt bin/update-config.sh


prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: nucleus-prod
  script:
    - CLUSTER_NAME=frankfurt bin/update-config.sh
