version: 1
update_configs:
  - package_manager: "python"
    update_schedule: "weekly"
    directory: "/"
    default_labels:
      - "maintenance"
      - "dependencies"
    ignored_updates:
      - match:
          dependency_name: "Django"
          version_requirement: "3.x"
